### ISSUE TITLE
Question: where are product reviews stored?

### ISSUE THREAD

**Issue by gerben86** [dutchwebdesign/magento2-kiyoh#1]
Hi @vince-dutchwebdesign ,

I'm looking into this module and I have one question:
are the Kiyoh Product reviews stored in the same table as the default Magento Product reviews, or do you use an alternative table?
Or are the productreviews retrieved from Kiyoh.com each time that the productpage is loaded?

Thanks in advance!

Regards,

Gerben

**Comment by dutchwebdesign** [comment]
Hi Gerben,

The kiyoh reviews are not stored in magento because this goes against their policies. The reviews are retrieved from their api and are stored as a cache string. When you or magento invalidate the cache the reviews are retrieved again. 

Regards,
