### ISSUE TITLE
Not able to disable sending review invitations per store

### ISSUE THREAD

**Issue by gerben86** [dutchwebdesign/magento2-kiyoh#2]
I have a multi-store Magento-instance.
Only for 1 store I'm using Kiyoh.
But I'm not able to disable this extension for the other stores. Because I can only set the language on store level:
![image](https://user-images.githubusercontent.com/17478858/99155006-9a528480-26b4-11eb-80b1-678759bb853c.png)

I'd like to have the option to en-/disable this plugin per store, because this will lead to strange situation where customers get a review-invitation for a store where they didn't buy anything....

**Comment by dutchwebdesign** [comment]
Hi Gerben,

Thanks for the feedback. We will take it with us for the upcomming releases

**Comment by gerben86** [comment]
@dutchwebdesign : does this mean that a new release is available?
