### ISSUE TITLE
Issue on category pages

### ISSUE THREAD

**Issue by shalinikat** [dutchwebdesign/magento2-kiyoh#3]
After enabling this extension, all the products on my category pages are gone. https://prnt.sc/voc35h

**Comment by dutchwebdesign** [comment]
Hi shalinikat, We test this module on the blank core theme from version 2.2. What version is your Magento? Can you show us the corresponding error which can be found in the logs.

**Comment by shalinikat** [comment]
*Magento* ver. 2.3.1

**Comment by dutchwebdesign** [comment]
Can you show us the corresponding error which can be found in the logs.
